query getAccountTopology($input: GetAccountTopologyInput!) {
  getAccountTopology(input: $input) {
    id
    name
    children {
      id
      name
      children {
        id
        name
      }
    }
  }
}
