query AccountBalance($input: AccountBalanceFilter!) {
  accountBalance(input: $input) {
    account {
      id
      name
    }
    accountGroup {
      id
      name
    }
    type
    balance
  }
}
