query getMonthlyAmountChangesDashboard($input: GetMonthlyAmountChangesInput!) {
  getAccountMonthlyAmountChanges(input: $input) {
    ...MonthlyAmountChangesData
  }
  getCategoryMonthlyAmountChanges(input: $input) {
    ...MonthlyAmountChangesData
  }
  getCategoryTypeMonthlyAmountChanges(input: $input) {
    ...MonthlyAmountChangesData
  }
}
