query getTransactions($input: GetTransactionsInput!) {
  getTransactions(input: $input) {
    id
    accrualDate
    note
    tags {
      id
      name
    }
    vaultId
    createdDate
    updatedDate
  }
}
