query getTransaction($input: GetTransactionInput!) {
  getTransaction(input: $input) {
    id
    accrualDate
    note
    tags {
      id
      name
    }
    treasuryBookId
    createdAt
    updatedAt
  }
}
