query getTransactionDetail(
  $getTransactionInput: GetTransactionInput!
  $getEntriesInput: GetEntriesInput!
) {
  getTransaction(input: $getTransactionInput) {
    ...TransactionData
    tags {
      id
      name
    }
  }
  getEntries(input: $getEntriesInput) {
    id
    treasuryBookId
    transactionDate
    debit
    credit
    memo
    account {
      id
      name
      category {
        id
        name
        type
      }
    }
    status
    transactionId
  }
}
