query getTransactionDetail($transactionId: String!) {
  getTransactionDetail(transactionId: $transactionId) {
    id
    accrualDate
    subject
    description
    amount
    count
    status
    tags {
      id
      name
    }
    entries {
      id
      transactionDate
      debit
      credit
      memo
      account {
        id
        name
      }
      status
    }
  }
}
