query getTransactionDetail(
  $getTransactionInput: GetTransactionInput!
  $getEntriesInput: GetEntriesInput!
) {
  getTransaction(input: $getTransactionInput) {
    id
    accrualDate
    note
    tags {
      id
      name
    }
    createdDate
    updatedDate
    vaultId
  }
  getEntries(input: $getEntriesInput) {
    id
    vaultId
    transactionDate
    debit
    credit
    memo
    account {
      id
      name
      category {
        id
        name
        type
      }
    }
    status
    transactionId
  }
}
