query TransactionDetails(
  $TransactionInput: TransactionInput!
  $getEntriesInput: GetEntriesInput!
) {
  transaction(input: $TransactionInput) {
    ...TransactionData
    updatedAt
    tags {
      id
      name
    }
  }
  getEntries(input: $getEntriesInput) {
    ...EntryData
  }
}
