query TransactionDetails(
  $TransactionInput: TransactionInput!
  $entriesInput: EntriesInput!
) {
  transaction(input: $TransactionInput) {
    ...TransactionData
    updatedAt
    tags {
      id
      name
    }
  }
  entries(input: $entriesInput) {
    ...EntryData
  }
}
