query ExchangeDetails(
  $exchangeInput: ExchangeInput!
  $entriesInput: EntriesInput!
) {
  exchange(input: $exchangeInput) {
    ...ExchangeData
    updatedAt
  }
  entries(input: $entriesInput) {
    ...EntryData
  }
}
