query getExchanges($input: GetExchangesInput!) {
  getExchanges(input: $input) {
    id
    ownerId
    origin {
      ...TransactionData
    }
    destination {
      ...TransactionData
    }
    createdAt
  }
}
