input BranchesInput {
  userId: String!
}

input BranchInput {
  id: String!
}

input AddBranchInput {
  userId: String!
  name: String!
  currency: Currency!
}

input UpdateBranchInput {
  id: String!
  name: String!
  currency: Currency!
}