query AccountDetail(
  $accountInput: AccountInput!
  $entriesInput: EntriesInput!
) {
  account(input: $accountInput) {
    ...AccountData
    updatedAt
  }
  entries(input: $entriesInput) {
    ...EntryData
  }
}
