query getAccountDetail(
  $getAccountInput: GetAccountInput!
  $entriesInput: EntriesInput!
) {
  getAccount(input: $getAccountInput) {
    ...AccountData
    updatedAt
  }
  entries(input: $entriesInput) {
    id
    treasuryBookId
    transactionDate
    debit
    credit
    memo
    account {
      id
      name
      category {
        id
        name
        type
      }
    }
    transactionId
    status
  }
}
