query getAccounts($input: GetAccountsInput!) {
  getAccounts(input: $input) {
    id
    category {
      id
      name
    }
    name
    entryCount
    treasuryBookId
    createdAt
    updatedAt
  }
}
