query getAccountDetail(
  $getAccountInput: GetAccountInput!
  $getEntriesInput: GetEntriesInput!
) {
  getAccount(input: $getAccountInput) {
    id
    name
    category {
      id
      name
    }
    createdAt
    updatedAt
  }
  getEntries(input: $getEntriesInput) {
    id
    treasuryBookId
    transactionDate
    debit
    credit
    memo
    account {
      id
      name
      category {
        id
        name
        type
      }
    }
    transactionId
    status
  }
}
