enum Currency {
  USD
  NTD
  EUR
  RMB
}

enum EntryStatus {
  PENDING
  COMPLETED
}

enum AccountingType {
  ASSETS
  LIABILITIES
  EQUITY  
}

enum CategoryType {
  ASSETS
  LIABILITIES
  EQUITY
}

enum TagType {
  GENERAL
  PEOPLE
  PROPERTY
  TRAVEL
  ORGANIZATION
}

enum DateType {
  TRANSACTION
  ACCRUAL
}

enum DateStandard {
  TRANSACTION
  ACCRUAL
}

enum ElementType {
  ACCOUNT
  ACCOUNT_GROUP
  ACCOUNTING_TYPE
}

enum LinkType {
  GENERAL
  FX
}
