type Mutation {
  # Account
  addAccount(input: AddAccountInput!): Account!
  updateAccount(input: UpdateAccountInput!): Account!

  # Transaction
  addTransaction(input: AddTransactionInput!): Transaction!
  updateTransaction(input: UpdateTransactionInput!): Transaction!

  # Link
  addLink(input: AddLinkInput!): Link!
  updateLink(input: UpdateLinkInput!): Link!

  # Tag
  addTag(input: AddTagInput!): Tag!
  updateTag(input: UpdateTagInput!): Tag!

  # Branch
  addBranch(input: AddBranchInput!): Branch!
  updateBranch(input: UpdateBranchInput!): Branch!

  # Account Group
  addAccountGroup(input: AddAccountGroupInput!): AccountGroup!
  updateAccountGroup(input: UpdateAccountGroupInput!): AccountGroup!

  # Journal
  addJournal(input: AddJournalInput!): Journal!
}
