type Mutation {
  # Account
  addAccount(input: AddAccountInput!): Account!
  updateAccount(input: UpdateAccountInput!): Account!

  # Category
  addCategory(input: AddCategoryInput!): Category!
  updateCategory(input: UpdateCategoryInput!): Category!

  # Transaction
  addTransaction(input: AddTransactionInput!): Transaction!
  updateTransaction(input: UpdateTransactionInput!): Transaction!

  # TreasuryBook
  addTreasuryBook(input: AddTreasuryBookInput!): TreasuryBook!
  updateTreasuryBook(input: UpdateTreasuryBookInput!): TreasuryBook!

  # Link
  addLink(input: AddLinkInput!): Link!
  updateLink(input: UpdateLinkInput!): Link!

  # Tag
  addTag(input: AddTagInput!): Tag!
  updateTag(input: UpdateTagInput!): Tag!

  # Branch
  addBranch(input: AddBranchInput!): Branch!
  updateBranch(input: UpdateBranchInput!): Branch!

  # Account Group
  addAccountGroup(input: AddAccountGroupInput!): AccountGroup!
  updateAccountGroup(input: UpdateAccountGroupInput!): AccountGroup!
}
