type Query {
  # Account
  account(input: AccountInput!): Account
  accounts(input: AccountsInput!): [Account!]!

  # Category
  categories(input: CategoriesInput!): [Category!]!
  category(input: CategoryInput!): Category

  # Entry
  entries(input: EntriesInput!): [Entry!]!

  # Report
  accountBalance(input: AccountBalanceFilter!): [AccountBalance!]!
  uniqueYears(input: UniqueYearsInput!): [Int!]!

  # Tag
  tag(input: TagInput!): Tag
  tags(input: TagsInput!): [Tag!]!

  # Transaction
  transaction(input: TransactionInput!): Transaction
  transactions(input: TransactionsInput!): [Transaction!]!

  # TreasuryBook
  treasuryBooks(input: TreasuryBooksInput!): [TreasuryBook!]!

  # Summary
  totalDebitAndCreditOverTheMonths(
    input: TotalDebitAndCreditOverTheMonthsInput!
  ): [TotalDebitAndCreditOverTheMonths!]!

  # Link
  links(input: LinksInput!): [Link!]!
  link(input: LinkInput!): Link

  # Journal
  journals(input: JournalsInput!): [Journal!]!
}
