input AccountGroupsInput {
  branchId: String!
}

input AccountGroupInput {
  id: String!
}

input AddAccountGroupInput {
  name: String!
  type: AccountingType!
  branchId: String!
}

input UpdateAccountGroupInput {
  id: String!
  name: String!
  type: AccountingType!
}
