type Account {
  id: String!
  name: String!
  category: Category!
  vaultId: String!
  createdDate: DateTime!
  updatedDate: DateTime!
}

type AccountDetail {
  id: String!
  name: String!
  category: Category!
  vaultId: String!
  createdDate: DateTime!
  updatedDate: DateTime!
  entries: [Entry!]!
}

input GetAccountsInput {
  vaultId: String!
  startDate: DateTime
  endDate: DateTime
  categoryId: [String!]
  nameSearch: String
}

input AddAccountInput {
  name: String!
  categoryId: String!
  vaultId: String!
}