type Account {
  id: String!
  name: String!
  category: Category
  entryCount: Int
  treasuryBookId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input AddAccountInput {
  name: String!
  categoryId: String!
  treasuryBookId: String!
}

input UpdateAccountInput {
  id: String!
  name: String!
  categoryId: String!
}

input GetAccountInput {
  id: String!
}

input GetAccountsInput {
  treasuryBookId: String!
  startDate: DateTime
  endDate: DateTime
  categoryId: String
  nameSearch: String
}
