input BranchInput {
  id: String!
}

input BranchesInput {
  active: Boolean!
}

input AddBranchInput {
  userId: String!
  name: String!
  currency: Currency!
}

input UpdateBranchInput {
  id: String!
  name: String!
  currency: Currency!
}

input HardDeleteBranchInput {
  id: String!
}

input DeleteBranchInput {
  id: String!
}
