type Category {
  id: String!
  name: String!
  type: CategoryType!
  vaultId: String!
  createdDate: DateTime!
  updatedDate: DateTime!
}

input GetCategoriesInput {
  vaultId: String!
  nameSearch: String
  type: CategoryType
}