type Category {
  id: String!
  name: String!
  type: CategoryType!
  treasuryBookId: String!
  accountCount: Int
  createdAt: DateTime!
  updatedAt: DateTime!
}

input AddCategoryInput {
  name: String!
  type: CategoryType!
  treasuryBookId: String!
}

input UpdateCategoryInput {
  id: String!
  name: String!
  type: CategoryType!
}

input CategoryInput {
  id: String!
}

input CategoriesInput {
  treasuryBookId: String!
}
