type Category {
  id: String!
  name: String!
  type: CategoryType!
  treasuryBookId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input AddCategoryInput {
  name: String!
  type: CategoryType!
  treasuryBookId: String!
}

input UpdateCategoryInput {
  id: String!
  name: String!
  type: CategoryType!
}

input GetCategoryInput {
  id: String!
}

input GetCategoriesInput {
  treasuryBookId: String!
  nameSearch: String
  type: CategoryType
}
