type AccountTopology {
  id: String!
  name: String!
  children: [AccountTopology!]!
}

type MinMaxDate {
  maxDate: DateTime
  minDate: DateTime
}

input GetAccountTopologyInput {
  vaultId: String!
}

input GetMinMaxDateInput {
  vaultId: String!
  basis: Basis!
}
