type Entry {
  id: String!
  treasuryBookId: String!
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  memo: String!
  account: Account
  transactionId: String!
  status: EntryStatus!
  createdAt: DateTime!
}

input AddEntryInput {
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  accountId: String!
  status: EntryStatus!
  memo: String!
}

input EntriesInput {
  treasuryBookId: String
  exchangeId: String
  transactionId: String
  status: EntryStatus
  accountId: String
  categoryType: String
  categoryId: String
}
