type Entry {
  id: String!
  vaultId: String!
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  memo: String
  account: Account!
  transactionId: String!
  status: EntryStatus!
}

input AddEntryInput {
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  accountId: String!
  status: EntryStatus!
  memo: String
}

input GetEntriesInput {
  vaultId: String
  startDate: DateTime
  endDate: DateTime
  transactionId: String
  status: EntryStatus
  memoSearch: String
  accountId: String
  categoryType: String
  categoryId: String
  debitAtLeast: Float
  debitNoMore: Float
  creditAtLeast: Float
  creditNoMore: Float
}