enum Currency {
  USD
  NTD
  EUR
  RMB
}

enum EntryStatus {
  PENDING
  COMPLETED
}

enum CategoryType {
  ASSETS
  LIABILITIES
  EQUITY
}

enum TagType {
  DEPRECIATION
  PREPAID
  ARAP
  CUSTOM
}

enum DateType {
  TRANSACTION
  ACCRUAL
}
