enum Currency {
  USD
  NTD
  EUR
  RMB
}

enum EntryStatus {
  PENDING
  COMPLETED
}

enum CategoryType {
  ASSETS
  LIABILITIES
  EQUITY
}

enum TagType {
  GENERAL
  PEOPLE
  PROPERTY
  TRAVEL
  ORGANIZATION
}

enum DateType {
  TRANSACTION
  ACCRUAL
}
