enum Currency {
  USD
  NTD
  EUR
  RMB
}

enum EntryStatus {
  PENDING
  COMPLETED
}

enum CategoryType {
  ASSETS
  LIABILITIES
  EQUITY
}

enum Basis {
  ACCRUAL
  CASH
}

enum ReportDateGroupBy {
  YEAR
  MONTH
  QUARTER
}

enum DateType {
  TRANSACTION
  ACCRUAL
}
