type Exchange {
  id: String!
  ownerId: String!
  origin: Transaction!
  destination: Transaction!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input AddExchangeInput {
  accrualDate: DateTime!
  ownerId: String!
  note: String!
  origin: AddExchangeTransactionInput!
  destination: AddExchangeTransactionInput!
}

input AddExchangeTransactionInput {
  treasuryBookId: String!
  entries: [AddEntryInput!]!
}

input GetExchangesInput {
  ownerId: String!
}

input GetExchangeInput {
  id: String!
}
