input JournalsInput {
  branchId: String
  tagId: String
  accountGroupId: String
  linkId: String
}

input JournalInput {
  id: String!
}

input AddJournalInput {
  branchId: String!
  note: String!
  accrualDate: DateTime!
  tags: [String!]!
  links: [String!]!
  entries: [AddJournalEntryInput!]!
}

input AddJournalEntryInput {
  memo: String!
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  status: EntryStatus!
  accountId: String!
}

input UpdateJournalInput {
  id: String!
  branchId: String!
  note: String!
  accrualDate: DateTime!
  tags: [String!]!
  links: [String!]!
  entries: [UpdateJournalEntryInput!]!
}

input UpdateJournalEntryInput {
  id: String
  memo: String!
  transactionDate: DateTime!
  debit: Float!
  credit: Float!
  status: EntryStatus!
  accountId: String!
}
