input LinksInput {
  userId: String!
}

input LinkInput {
  id: String!
}

input AddLinkInput {
  userId: String!
  name: String!
  type: LinkType!
}

input UpdateLinkInput {
  id: String!
  name: String!
  type: LinkType!
}