type Mutation {
  # Account
  addAccount(input: AddAccountInput!): Account!

  # Category
  addCategory(input: AddCategoryInput!): Category!

  # Vault
  addVault(input: AddVaultInput!): Vault!

  # Tag
  addTag(input: AddTagInput!): Tag!
}
