type Mutation {
  # Account
  addAccount(input: AddAccountInput!): Account!
  updateAccount(input: UpdateAccountInput!): Account!

  # Category
  addCategory(input: AddCategoryInput!): Category!

  # Tag
  addTag(input: AddTagInput!): Tag!

  # Transaction
  addTransaction(input: AddTransactionInput!): Transaction!
  updateTransaction(input: UpdateTransactionInput!): Transaction!

  # Vault
  addVault(input: AddVaultInput!): Vault!

}
