type Mutation {
  # Account
  addAccount(input: AddAccountInput!): Account!

  # Category
  addCategory(input: AddCategoryInput!): Category!

  # Tag
  addTag(input: AddTagInput!): Tag!

  # Transaction
  addTransaction(input: AddTransactionInput): Transaction

  # Vault
  addVault(input: AddVaultInput!): Vault!

}
