type Query {
  # Vault
  getAllVaults(ownerId: String!): [Vault!]!

  # Transaction
  getAllTransactions(vaultId: String!): [Transaction!]!
  getTransactionDetail(transactionId: String!): Transaction

  # Entry
  getEntries(input: GetEntriesInput!): [Entry!]!
}