type Query {
  # Account
  getAccount(input: GetAccountInput!): Account
  getAccounts(input: GetAccountsInput!): [Account!]!

  # Category
  getCategories(input: GetCategoriesInput!): [Category!]!
  getCategory(input: GetCategoryInput!): Category

  # Entry
  getEntries(input: GetEntriesInput!): [Entry!]!

  # Report
  getAccountMonthlyChanges(input: GetMonthlyAmountInput!): [MonthlyAmount!]!
  getCategoryMonthlyChanges(input: GetMonthlyAmountInput!): [MonthlyAmount!]!
  getCategoryTypeMonthlyChanges(
    input: GetMonthlyAmountInput!
  ): [MonthlyAmount!]!
  getAccountMonthlyBalance(input: GetMonthlyAmountInput!): [MonthlyAmount!]!
  getCategoryMonthlyBalance(input: GetMonthlyAmountInput!): [MonthlyAmount!]!
  getCategoryTypeMonthlyBalance(
    input: GetMonthlyAmountInput!
  ): [MonthlyAmount!]!
  getUniqueYears(input: GetUniqueYearsInput!): [Int!]!

  # Tag
  getTag(input: GetTagInput!): Tag
  getTags(input: GetTagsInput!): [Tag!]!

  # Transaction
  getTransaction(input: GetTransactionInput!): Transaction
  getTransactionDetail(transactionId: String!): Transaction
  getTransactions(input: GetTransactionsInput!): [Transaction!]!

  # TreasuryBook
  getTreasuryBooks(input: GetTreasuryBooksInput!): [TreasuryBook!]!
}
