type Query {
  # Account
  account(input: AccountInput!): Account
  accounts(input: AccountsInput!): [Account!]!

  # Category
  categories(input: CategoriesInput!): [Category!]!
  category(input: CategoryInput!): Category

  # Entry
  entries(input: EntriesInput!): [Entry!]!

  # Report
  accountMonthlyChanges(input: MonthlyAmountInput!): [MonthlyAmount!]!
  categoryMonthlyChanges(input: MonthlyAmountInput!): [MonthlyAmount!]!
  categoryTypeMonthlyChanges(input: MonthlyAmountInput!): [MonthlyAmount!]!
  accountBalance(input: AccountBalanceFilter!): [Balance!]!
  accountMonthlyBalance(input: MonthlyAmountInput!): [MonthlyAmount!]!
  categoryMonthlyBalance(input: MonthlyAmountInput!): [MonthlyAmount!]!
  categoryTypeMonthlyBalance(input: MonthlyAmountInput!): [MonthlyAmount!]!
  uniqueYears(input: UniqueYearsInput!): [Int!]!

  # Tag
  tag(input: TagInput!): Tag
  tags(input: TagsInput!): [Tag!]!

  # Transaction
  transaction(input: TransactionInput!): Transaction
  transactions(input: TransactionsInput!): [Transaction!]!

  # TreasuryBook
  treasuryBooks(input: TreasuryBooksInput!): [TreasuryBook!]!

  # Exchange
  exchanges(input: ExchangesInput!): [Exchange!]!
  exchange(input: ExchangeInput!): Exchange
}
