type Amount {
  credit: Float!
  debit: Float!
}

type AmountOnMonth {
  month: Int!
  amount: Amount!
}

type MonthlyAmount {
  id: String!
  name: String!
  amounts: [AmountOnMonth!]!
}

input GetMonthlyAmountInput {
  year: Int
  treasuryBookId: String!
  type: DateType!
  status: EntryStatus
}

input GetUniqueYearsInput {
  treasuryBookId: String!
  type: DateType!
}
