type Tag {
  name: String!
  id: String!
  count: Int!
  type: TagType!
  treasuryBookId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input AddTagInput {
  name: String!
  treasuryBookId: String!
  type: TagType!
}

input UpdateTagInput {
  id: String!
  name: String!
  type: TagType!
}

input TagInput {
  id: String!
}

input TagsInput {
  treasuryBookId: String!
}
