type Transaction {
  id: String!
  accrualDate: DateTime!
  note: String!
  tags: [Tag!]!
  vaultId: String!
  createdDate: DateTime!
  updatedDate: DateTime!
  # status is not part of the prisma schema but a calculated field from the entries table
  # we need this field to show the status of transactions in a table without doing another query
  status: EntryStatus
  # entries is returned when adding a new transaction to confirm the result
  entries: [Entry!]
}

input AddTransactionInput {
  accrualDate: DateTime!
  note: String!
  tagIds: [String!]!
  vaultId: String!
  entries: [AddEntryInput!]!
}

input UpdateTransactionInput {
  id: String!
  accrualDate: DateTime!
  note: String!
  tagIds: [String!]!
  vaultId: String!
  entries: [AddEntryInput!]!
}

input GetTransactionInput {
  id: String!
}

input GetTransactionsInput {
  vaultId: String!
  tagId: String
  status: EntryStatus
}
