type Transaction {
  id: String!
  accrualDate: DateTime!
  note: String!
  tags: [Tag!]!
  vaultId: String!
  status: EntryStatus
  createdDate: DateTime!
  updatedDate: DateTime!
}

input GetTransactionInput {
  id: String!
}

input GetTransactionsInput {
  vaultId: String!
  tagId: String
  startDate: DateTime
  endDate: DateTime
  noteSearch: String
}