type Transaction {
  id: String!
  accrualDate: DateTime!
  note: String!
  amount: Float!
  count: Int!
  status: Status!
  tags: [Tag!]!
  entries: [Entry!]!
  createdDate: DateTime!
  updatedDate: DateTime!
}
