type TreasuryBook {
  id: String!
  name: String!
  currency: Currency!
  ownerId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

input GetTreasuryBooksInput {
  ownerId: String!
  currency: Currency
}

input AddTreasuryBookInput {
  name: String!
  currency: Currency!
  ownerId: String!
}
