type Vault {
  id: String!
  name: String!
  currency: Currency!
  ownerId: String!
  createdDate: DateTime!
  updatedDate: DateTime!
}

input GetVaultsInput {
  ownerId: String!
  nameSearch: String
  currency: Currency
}

input AddVaultInput {
  name: String!
  currency: Currency!
  ownerId: String!
}
