query tagDetail(
  $TagInput: TagInput!
  $TransactionsInput: TransactionsInput!
) {
  tag(input: $TagInput) {
    ...TagData
    updatedAt
  }
  transactions(input: $TransactionsInput) {
    ...TransactionData
  }
}
