query getTagDetail(
  $getTagInput: GetTagInput!
  $TransactionsInput: TransactionsInput!
) {
  getTag(input: $getTagInput) {
    id
    name
    treasuryBookId
    createdAt
    updatedAt
  }
  transactions(input: $TransactionsInput) {
    ...TransactionData
  }
}
