query TagDetails($tagInput: TagInput!, $transactionsInput: TransactionsInput!) {
  tag(input: $tagInput) {
    ...TagData
    updatedAt
  }
  transactions(input: $transactionsInput) {
    ...TransactionData
  }
}
