fragment EntryData on Entry {
  id
  treasuryBookId
  transactionDate
  debit
  credit
  memo
  account {
    id
    name
    accountGroup {
      id
      name
      type
    }
  }
  status
  transactionId
  createdAt
}
