query Journal($input: JournalInput!) {
  journal(input: $input) {
    ...JournalData
    branchId
    updatedAt
    deletedAt
    links {
      id
      name
    }
    tags {
      id
      name
    }
    currency
  }
}
