query TotalDebitAndCreditOverTheMonths(
  $input: TotalDebitAndCreditOverTheMonthsInput!
) {
  totalDebitAndCreditOverTheMonths(input: $input) {
    id
    name
    total {
      debit
      credit
    }
  }
}
