query getCategoryDetail(
  $getCategoryInput: GetCategoryInput!
  $getAccountsInput: GetAccountsInput!
  $entriesInput: EntriesInput!
) {
  getCategory(input: $getCategoryInput) {
    id
    name
    type
    createdAt
    updatedAt
  }
  getAccounts(input: $getAccountsInput) {
    ...AccountData
  }
  entries(input: $entriesInput) {
    id
    treasuryBookId
    transactionDate
    debit
    credit
    memo
    account {
      id
      name
      category {
        id
        name
        type
      }
    }
    transactionId
    status
  }
}
